import { Customer, AIInsight, Notification, AIModelUsage, AIUsageSummary, TeamMember, PipelineDeal, Recommendation } from "./types";

const months = ["Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun"];

function generateTrend(baseRevenue: number, baseSupportCost: number, baseEngCost: number, baseEngagement: number, baseTickets: number, declining = false) {
  return months.map((month, i) => {
    const factor = declining ? 1 - i * 0.03 : 1 + (Math.random() - 0.4) * 0.05;
    const noise = () => 0.85 + Math.random() * 0.3;
    return {
      month,
      revenue: Math.round(baseRevenue * (declining ? factor : noise())),
      supportCost: Math.round(baseSupportCost * (declining ? 1 + i * 0.04 : noise())),
      engineeringCost: Math.round(baseEngCost * noise()),
      engagement: Math.round(Math.min(100, Math.max(5, baseEngagement * (declining ? factor : noise())))),
      tickets: Math.round(Math.max(0, baseTickets * (declining ? 1 + i * 0.05 : noise()))),
    };
  });
}

export const customers: Customer[] = [
  {
    id: "cust-001",
    name: "Acme Corporation",
    logo: "AC",
    segment: "Enterprise",
    industry: "Financial Services",
    accountOwner: "Sarah Chen",
    lifecycleStage: "Active",
    onboardingStatus: "Complete",
    companySize: 2500,
    leadSource: "Outbound Sales",
    arr: 480000,
    mrr: 40000,
    contractValue: 520000,
    subscriptionStatus: "Active",
    billingCycle: "Annual",
    failedPayments: 0,
    lastPaymentDate: "2026-05-01",
    paymentHistory: [
      { date: "2026-05-01", amount: 40000, status: "Paid" },
      { date: "2026-04-01", amount: 40000, status: "Paid" },
      { date: "2026-03-01", amount: 40000, status: "Paid" },
    ],
    upgrades: 2,
    downgrades: 0,
    ticketCount: 12,
    unresolvedTickets: 1,
    escalations: 0,
    slaBreaches: 0,
    csatScore: 94,
    supportHours: 18,
    issueCategories: ["Integration", "API"],
    engineeringHours: 45,
    activeProjects: 2,
    delayedTasks: 0,
    bugCount: 3,
    sprintVelocity: 42,
    activeUsers: 380,
    featureAdoption: 87,
    loginFrequency: 92,
    engagementScore: 91,
    featureUsageDecline: 0,
    sessionActivity: 4200,
    supportCost: 2700,
    engineeringCost: 6750,
    operationalCost: 9450,
    profitabilityScore: 92,
    marginPercentage: 76.4,
    healthScore: 93,
    churnRiskScore: 8,
    renewalDate: "2026-11-15",
    renewalValue: 520000,
    recentActivity: [
      { date: "2026-05-24", type: "product", description: "API usage increased 23% MoM", severity: "info" },
      { date: "2026-05-22", type: "support", description: "Integration ticket resolved in 2h", severity: "info" },
      { date: "2026-05-20", type: "billing", description: "Annual payment processed", severity: "info" },
    ],
    churnSignals: [],
    monthlyTrend: generateTrend(40000, 2700, 6750, 91, 12),
  },
  {
    id: "cust-002",
    name: "NovaTech Solutions",
    logo: "NT",
    segment: "Enterprise",
    industry: "Technology",
    accountOwner: "Marcus Rivera",
    lifecycleStage: "At Risk",
    onboardingStatus: "Complete",
    companySize: 1800,
    leadSource: "Partner Referral",
    arr: 360000,
    mrr: 30000,
    contractValue: 380000,
    subscriptionStatus: "Active",
    billingCycle: "Annual",
    failedPayments: 2,
    lastPaymentDate: "2026-04-15",
    paymentHistory: [
      { date: "2026-04-15", amount: 30000, status: "Paid" },
      { date: "2026-03-15", amount: 30000, status: "Failed" },
      { date: "2026-02-15", amount: 30000, status: "Failed" },
    ],
    upgrades: 0,
    downgrades: 1,
    ticketCount: 47,
    unresolvedTickets: 12,
    escalations: 5,
    slaBreaches: 3,
    csatScore: 52,
    supportHours: 86,
    issueCategories: ["Performance", "Bugs", "Data Sync", "Billing"],
    engineeringHours: 180,
    activeProjects: 4,
    delayedTasks: 7,
    bugCount: 18,
    sprintVelocity: 28,
    activeUsers: 210,
    featureAdoption: 41,
    loginFrequency: 38,
    engagementScore: 34,
    featureUsageDecline: 48,
    sessionActivity: 1100,
    supportCost: 12900,
    engineeringCost: 27000,
    operationalCost: 39900,
    profitabilityScore: 18,
    marginPercentage: -10.8,
    healthScore: 28,
    churnRiskScore: 82,
    renewalDate: "2026-08-01",
    renewalValue: 360000,
    recentActivity: [
      { date: "2026-05-25", type: "support", description: "3 tickets escalated to engineering", severity: "critical" },
      { date: "2026-05-24", type: "product", description: "Daily active users down 48% in 30 days", severity: "critical" },
      { date: "2026-05-22", type: "billing", description: "Payment retry succeeded after 2 failures", severity: "warning" },
      { date: "2026-05-20", type: "account", description: "Champion contact left the company", severity: "critical" },
    ],
    churnSignals: [
      { signal: "Feature adoption declined 48% in 30 days", severity: "critical", source: "Mixpanel", detectedDate: "2026-05-24" },
      { signal: "2 consecutive failed payments", severity: "high", source: "Stripe", detectedDate: "2026-03-15" },
      { signal: "5 support escalations this quarter", severity: "high", source: "Zendesk", detectedDate: "2026-05-25" },
      { signal: "Champion contact departed", severity: "critical", source: "HubSpot", detectedDate: "2026-05-20" },
    ],
    monthlyTrend: generateTrend(30000, 12900, 27000, 34, 47, true),
  },
  {
    id: "cust-003",
    name: "Delta SaaS Group",
    logo: "DS",
    segment: "Enterprise",
    industry: "Healthcare",
    accountOwner: "Sarah Chen",
    lifecycleStage: "Active",
    onboardingStatus: "Complete",
    companySize: 3200,
    leadSource: "Inbound Marketing",
    arr: 720000,
    mrr: 60000,
    contractValue: 780000,
    subscriptionStatus: "Active",
    billingCycle: "Annual",
    failedPayments: 0,
    lastPaymentDate: "2026-05-10",
    paymentHistory: [
      { date: "2026-05-10", amount: 60000, status: "Paid" },
      { date: "2026-04-10", amount: 60000, status: "Paid" },
    ],
    upgrades: 3,
    downgrades: 0,
    ticketCount: 28,
    unresolvedTickets: 4,
    escalations: 1,
    slaBreaches: 0,
    csatScore: 88,
    supportHours: 42,
    issueCategories: ["Feature Request", "Integration", "Training"],
    engineeringHours: 95,
    activeProjects: 3,
    delayedTasks: 1,
    bugCount: 5,
    sprintVelocity: 38,
    activeUsers: 620,
    featureAdoption: 78,
    loginFrequency: 85,
    engagementScore: 82,
    featureUsageDecline: 5,
    sessionActivity: 6800,
    supportCost: 6300,
    engineeringCost: 14250,
    operationalCost: 20550,
    profitabilityScore: 85,
    marginPercentage: 71.5,
    healthScore: 84,
    churnRiskScore: 15,
    renewalDate: "2027-01-20",
    renewalValue: 780000,
    recentActivity: [
      { date: "2026-05-24", type: "product", description: "Adopted 3 new features this month", severity: "info" },
      { date: "2026-05-21", type: "account", description: "Contract expansion discussion initiated", severity: "info" },
    ],
    churnSignals: [],
    monthlyTrend: generateTrend(60000, 6300, 14250, 82, 28),
  },
  {
    id: "cust-004",
    name: "Pinnacle Ventures",
    logo: "PV",
    segment: "Mid-Market",
    industry: "Venture Capital",
    accountOwner: "James Park",
    lifecycleStage: "Active",
    onboardingStatus: "Complete",
    companySize: 120,
    leadSource: "Outbound Sales",
    arr: 96000,
    mrr: 8000,
    contractValue: 96000,
    subscriptionStatus: "Active",
    billingCycle: "Monthly",
    failedPayments: 0,
    lastPaymentDate: "2026-05-01",
    paymentHistory: [
      { date: "2026-05-01", amount: 8000, status: "Paid" },
      { date: "2026-04-01", amount: 8000, status: "Paid" },
    ],
    upgrades: 1,
    downgrades: 0,
    ticketCount: 5,
    unresolvedTickets: 0,
    escalations: 0,
    slaBreaches: 0,
    csatScore: 96,
    supportHours: 6,
    issueCategories: ["Onboarding"],
    engineeringHours: 10,
    activeProjects: 0,
    delayedTasks: 0,
    bugCount: 1,
    sprintVelocity: 0,
    activeUsers: 45,
    featureAdoption: 72,
    loginFrequency: 80,
    engagementScore: 78,
    featureUsageDecline: 2,
    sessionActivity: 520,
    supportCost: 900,
    engineeringCost: 1500,
    operationalCost: 2400,
    profitabilityScore: 90,
    marginPercentage: 75.0,
    healthScore: 88,
    churnRiskScore: 10,
    renewalDate: "2026-12-01",
    renewalValue: 96000,
    recentActivity: [
      { date: "2026-05-23", type: "product", description: "Team added 5 new users", severity: "info" },
    ],
    churnSignals: [],
    monthlyTrend: generateTrend(8000, 900, 1500, 78, 5),
  },
  {
    id: "cust-005",
    name: "Orbital Dynamics",
    logo: "OD",
    segment: "Mid-Market",
    industry: "Aerospace",
    accountOwner: "Marcus Rivera",
    lifecycleStage: "At Risk",
    onboardingStatus: "Complete",
    companySize: 450,
    leadSource: "Conference",
    arr: 144000,
    mrr: 12000,
    contractValue: 156000,
    subscriptionStatus: "Past Due",
    billingCycle: "Annual",
    failedPayments: 3,
    lastPaymentDate: "2026-03-01",
    paymentHistory: [
      { date: "2026-05-01", amount: 12000, status: "Failed" },
      { date: "2026-04-01", amount: 12000, status: "Failed" },
      { date: "2026-03-01", amount: 12000, status: "Paid" },
    ],
    upgrades: 0,
    downgrades: 2,
    ticketCount: 31,
    unresolvedTickets: 8,
    escalations: 4,
    slaBreaches: 2,
    csatScore: 45,
    supportHours: 62,
    issueCategories: ["Performance", "Downtime", "Data Loss"],
    engineeringHours: 120,
    activeProjects: 2,
    delayedTasks: 5,
    bugCount: 14,
    sprintVelocity: 22,
    activeUsers: 65,
    featureAdoption: 33,
    loginFrequency: 28,
    engagementScore: 25,
    featureUsageDecline: 55,
    sessionActivity: 380,
    supportCost: 9300,
    engineeringCost: 18000,
    operationalCost: 27300,
    profitabilityScore: 12,
    marginPercentage: -18.9,
    healthScore: 22,
    churnRiskScore: 89,
    renewalDate: "2026-07-15",
    renewalValue: 144000,
    recentActivity: [
      { date: "2026-05-25", type: "billing", description: "Third consecutive payment failure", severity: "critical" },
      { date: "2026-05-23", type: "support", description: "Data loss incident reported", severity: "critical" },
      { date: "2026-05-21", type: "product", description: "Active users dropped to 65 from 180", severity: "critical" },
    ],
    churnSignals: [
      { signal: "3 consecutive failed payments", severity: "critical", source: "Stripe", detectedDate: "2026-05-01" },
      { signal: "Active users declined 64%", severity: "critical", source: "Mixpanel", detectedDate: "2026-05-21" },
      { signal: "2 SLA breaches in 30 days", severity: "high", source: "Zendesk", detectedDate: "2026-05-15" },
      { signal: "2 product downgrades", severity: "medium", source: "Stripe", detectedDate: "2026-04-10" },
    ],
    monthlyTrend: generateTrend(12000, 9300, 18000, 25, 31, true),
  },
  {
    id: "cust-006",
    name: "CloudScale AI",
    logo: "CA",
    segment: "Enterprise",
    industry: "AI / Machine Learning",
    accountOwner: "Sarah Chen",
    lifecycleStage: "Active",
    onboardingStatus: "Complete",
    companySize: 800,
    leadSource: "Product-Led Growth",
    arr: 540000,
    mrr: 45000,
    contractValue: 600000,
    subscriptionStatus: "Active",
    billingCycle: "Annual",
    failedPayments: 0,
    lastPaymentDate: "2026-05-05",
    paymentHistory: [
      { date: "2026-05-05", amount: 45000, status: "Paid" },
      { date: "2026-04-05", amount: 45000, status: "Paid" },
    ],
    upgrades: 4,
    downgrades: 0,
    ticketCount: 8,
    unresolvedTickets: 1,
    escalations: 0,
    slaBreaches: 0,
    csatScore: 97,
    supportHours: 12,
    issueCategories: ["Feature Request", "API"],
    engineeringHours: 30,
    activeProjects: 1,
    delayedTasks: 0,
    bugCount: 2,
    sprintVelocity: 45,
    activeUsers: 520,
    featureAdoption: 94,
    loginFrequency: 96,
    engagementScore: 95,
    featureUsageDecline: 0,
    sessionActivity: 7800,
    supportCost: 1800,
    engineeringCost: 4500,
    operationalCost: 6300,
    profitabilityScore: 96,
    marginPercentage: 86.0,
    healthScore: 96,
    churnRiskScore: 4,
    renewalDate: "2027-03-01",
    renewalValue: 650000,
    recentActivity: [
      { date: "2026-05-24", type: "account", description: "Expansion deal in pipeline - $110K", severity: "info" },
      { date: "2026-05-22", type: "product", description: "Highest engagement score in portfolio", severity: "info" },
    ],
    churnSignals: [],
    monthlyTrend: generateTrend(45000, 1800, 4500, 95, 8),
  },
  {
    id: "cust-007",
    name: "UrbanGrid Logistics",
    logo: "UG",
    segment: "Mid-Market",
    industry: "Logistics",
    accountOwner: "James Park",
    lifecycleStage: "Active",
    onboardingStatus: "Complete",
    companySize: 350,
    leadSource: "Inbound Marketing",
    arr: 108000,
    mrr: 9000,
    contractValue: 108000,
    subscriptionStatus: "Active",
    billingCycle: "Monthly",
    failedPayments: 1,
    lastPaymentDate: "2026-05-01",
    paymentHistory: [
      { date: "2026-05-01", amount: 9000, status: "Paid" },
      { date: "2026-04-01", amount: 9000, status: "Failed" },
      { date: "2026-03-01", amount: 9000, status: "Paid" },
    ],
    upgrades: 0,
    downgrades: 0,
    ticketCount: 18,
    unresolvedTickets: 3,
    escalations: 1,
    slaBreaches: 1,
    csatScore: 71,
    supportHours: 28,
    issueCategories: ["Integration", "Performance", "Training"],
    engineeringHours: 35,
    activeProjects: 1,
    delayedTasks: 2,
    bugCount: 6,
    sprintVelocity: 30,
    activeUsers: 92,
    featureAdoption: 58,
    loginFrequency: 62,
    engagementScore: 60,
    featureUsageDecline: 12,
    sessionActivity: 890,
    supportCost: 4200,
    engineeringCost: 5250,
    operationalCost: 9450,
    profitabilityScore: 58,
    marginPercentage: 47.5,
    healthScore: 62,
    churnRiskScore: 38,
    renewalDate: "2026-09-30",
    renewalValue: 108000,
    recentActivity: [
      { date: "2026-05-23", type: "support", description: "SLA breach on priority ticket", severity: "warning" },
      { date: "2026-05-20", type: "product", description: "Feature usage trending down 12%", severity: "warning" },
    ],
    churnSignals: [
      { signal: "Feature usage declining 12%", severity: "medium", source: "Mixpanel", detectedDate: "2026-05-20" },
      { signal: "1 SLA breach this month", severity: "medium", source: "Zendesk", detectedDate: "2026-05-23" },
    ],
    monthlyTrend: generateTrend(9000, 4200, 5250, 60, 18),
  },
  {
    id: "cust-008",
    name: "Meridian Health Systems",
    logo: "MH",
    segment: "Enterprise",
    industry: "Healthcare IT",
    accountOwner: "Sarah Chen",
    lifecycleStage: "Active",
    onboardingStatus: "Complete",
    companySize: 4100,
    leadSource: "Outbound Sales",
    arr: 960000,
    mrr: 80000,
    contractValue: 1100000,
    subscriptionStatus: "Active",
    billingCycle: "Annual",
    failedPayments: 0,
    lastPaymentDate: "2026-05-15",
    paymentHistory: [
      { date: "2026-05-15", amount: 80000, status: "Paid" },
      { date: "2026-04-15", amount: 80000, status: "Paid" },
    ],
    upgrades: 5,
    downgrades: 0,
    ticketCount: 22,
    unresolvedTickets: 3,
    escalations: 1,
    slaBreaches: 0,
    csatScore: 91,
    supportHours: 35,
    issueCategories: ["Compliance", "Integration", "Feature Request"],
    engineeringHours: 65,
    activeProjects: 2,
    delayedTasks: 0,
    bugCount: 4,
    sprintVelocity: 40,
    activeUsers: 890,
    featureAdoption: 83,
    loginFrequency: 88,
    engagementScore: 86,
    featureUsageDecline: 0,
    sessionActivity: 9200,
    supportCost: 5250,
    engineeringCost: 9750,
    operationalCost: 15000,
    profitabilityScore: 93,
    marginPercentage: 81.3,
    healthScore: 91,
    churnRiskScore: 6,
    renewalDate: "2027-05-01",
    renewalValue: 1100000,
    recentActivity: [
      { date: "2026-05-24", type: "account", description: "Multi-year contract renewal discussion", severity: "info" },
    ],
    churnSignals: [],
    monthlyTrend: generateTrend(80000, 5250, 9750, 86, 22),
  },
  {
    id: "cust-009",
    name: "Vertex Analytics",
    logo: "VA",
    segment: "SMB",
    industry: "Data Analytics",
    accountOwner: "James Park",
    lifecycleStage: "Churning",
    onboardingStatus: "Complete",
    companySize: 45,
    leadSource: "Product-Led Growth",
    arr: 24000,
    mrr: 2000,
    contractValue: 24000,
    subscriptionStatus: "Past Due",
    billingCycle: "Monthly",
    failedPayments: 4,
    lastPaymentDate: "2026-02-01",
    paymentHistory: [
      { date: "2026-05-01", amount: 2000, status: "Failed" },
      { date: "2026-04-01", amount: 2000, status: "Failed" },
      { date: "2026-03-01", amount: 2000, status: "Failed" },
      { date: "2026-02-01", amount: 2000, status: "Paid" },
    ],
    upgrades: 0,
    downgrades: 1,
    ticketCount: 15,
    unresolvedTickets: 6,
    escalations: 3,
    slaBreaches: 4,
    csatScore: 28,
    supportHours: 32,
    issueCategories: ["Bugs", "Billing", "Downtime"],
    engineeringHours: 48,
    activeProjects: 1,
    delayedTasks: 3,
    bugCount: 9,
    sprintVelocity: 15,
    activeUsers: 3,
    featureAdoption: 12,
    loginFrequency: 8,
    engagementScore: 10,
    featureUsageDecline: 82,
    sessionActivity: 45,
    supportCost: 4800,
    engineeringCost: 7200,
    operationalCost: 12000,
    profitabilityScore: 5,
    marginPercentage: -50.0,
    healthScore: 8,
    churnRiskScore: 96,
    renewalDate: "2026-06-15",
    renewalValue: 24000,
    recentActivity: [
      { date: "2026-05-25", type: "billing", description: "4th consecutive failed payment", severity: "critical" },
      { date: "2026-05-24", type: "product", description: "Only 3 active users remaining", severity: "critical" },
      { date: "2026-05-22", type: "support", description: "Customer requested cancellation info", severity: "critical" },
    ],
    churnSignals: [
      { signal: "Requested cancellation information", severity: "critical", source: "Zendesk", detectedDate: "2026-05-22" },
      { signal: "4 consecutive failed payments", severity: "critical", source: "Stripe", detectedDate: "2026-05-01" },
      { signal: "Usage declined 82%", severity: "critical", source: "Mixpanel", detectedDate: "2026-05-24" },
      { signal: "Only 3 of 45 users active", severity: "critical", source: "Mixpanel", detectedDate: "2026-05-24" },
    ],
    monthlyTrend: generateTrend(2000, 4800, 7200, 10, 15, true),
  },
  {
    id: "cust-010",
    name: "Beacon Financial",
    logo: "BF",
    segment: "Mid-Market",
    industry: "FinTech",
    accountOwner: "Marcus Rivera",
    lifecycleStage: "Active",
    onboardingStatus: "Complete",
    companySize: 280,
    leadSource: "Partner Referral",
    arr: 192000,
    mrr: 16000,
    contractValue: 210000,
    subscriptionStatus: "Active",
    billingCycle: "Annual",
    failedPayments: 0,
    lastPaymentDate: "2026-05-08",
    paymentHistory: [
      { date: "2026-05-08", amount: 16000, status: "Paid" },
      { date: "2026-04-08", amount: 16000, status: "Paid" },
    ],
    upgrades: 1,
    downgrades: 0,
    ticketCount: 9,
    unresolvedTickets: 1,
    escalations: 0,
    slaBreaches: 0,
    csatScore: 90,
    supportHours: 14,
    issueCategories: ["Integration", "Feature Request"],
    engineeringHours: 20,
    activeProjects: 1,
    delayedTasks: 0,
    bugCount: 2,
    sprintVelocity: 35,
    activeUsers: 165,
    featureAdoption: 76,
    loginFrequency: 82,
    engagementScore: 79,
    featureUsageDecline: 0,
    sessionActivity: 1800,
    supportCost: 2100,
    engineeringCost: 3000,
    operationalCost: 5100,
    profitabilityScore: 88,
    marginPercentage: 73.4,
    healthScore: 85,
    churnRiskScore: 12,
    renewalDate: "2027-02-15",
    renewalValue: 210000,
    recentActivity: [
      { date: "2026-05-22", type: "product", description: "Onboarded 20 new team members", severity: "info" },
    ],
    churnSignals: [],
    monthlyTrend: generateTrend(16000, 2100, 3000, 79, 9),
  },
  {
    id: "cust-011",
    name: "Stratos Cloud",
    logo: "SC",
    segment: "SMB",
    industry: "Cloud Infrastructure",
    accountOwner: "James Park",
    lifecycleStage: "Active",
    onboardingStatus: "Complete",
    companySize: 65,
    leadSource: "Product-Led Growth",
    arr: 36000,
    mrr: 3000,
    contractValue: 36000,
    subscriptionStatus: "Active",
    billingCycle: "Monthly",
    failedPayments: 0,
    lastPaymentDate: "2026-05-01",
    paymentHistory: [
      { date: "2026-05-01", amount: 3000, status: "Paid" },
    ],
    upgrades: 1,
    downgrades: 0,
    ticketCount: 3,
    unresolvedTickets: 0,
    escalations: 0,
    slaBreaches: 0,
    csatScore: 92,
    supportHours: 4,
    issueCategories: ["Onboarding"],
    engineeringHours: 5,
    activeProjects: 0,
    delayedTasks: 0,
    bugCount: 0,
    sprintVelocity: 0,
    activeUsers: 38,
    featureAdoption: 68,
    loginFrequency: 75,
    engagementScore: 72,
    featureUsageDecline: 0,
    sessionActivity: 420,
    supportCost: 600,
    engineeringCost: 750,
    operationalCost: 1350,
    profitabilityScore: 91,
    marginPercentage: 81.3,
    healthScore: 82,
    churnRiskScore: 14,
    renewalDate: "2026-10-01",
    renewalValue: 36000,
    recentActivity: [
      { date: "2026-05-20", type: "product", description: "Upgraded to Pro plan", severity: "info" },
    ],
    churnSignals: [],
    monthlyTrend: generateTrend(3000, 600, 750, 72, 3),
  },
  {
    id: "cust-012",
    name: "Forge Manufacturing",
    logo: "FM",
    segment: "Enterprise",
    industry: "Manufacturing",
    accountOwner: "Sarah Chen",
    lifecycleStage: "Active",
    onboardingStatus: "Complete",
    companySize: 5200,
    leadSource: "Outbound Sales",
    arr: 420000,
    mrr: 35000,
    contractValue: 450000,
    subscriptionStatus: "Active",
    billingCycle: "Annual",
    failedPayments: 0,
    lastPaymentDate: "2026-05-12",
    paymentHistory: [
      { date: "2026-05-12", amount: 35000, status: "Paid" },
      { date: "2026-04-12", amount: 35000, status: "Paid" },
    ],
    upgrades: 2,
    downgrades: 0,
    ticketCount: 15,
    unresolvedTickets: 2,
    escalations: 0,
    slaBreaches: 0,
    csatScore: 87,
    supportHours: 22,
    issueCategories: ["Integration", "Training", "Feature Request"],
    engineeringHours: 55,
    activeProjects: 2,
    delayedTasks: 1,
    bugCount: 4,
    sprintVelocity: 36,
    activeUsers: 340,
    featureAdoption: 71,
    loginFrequency: 78,
    engagementScore: 75,
    featureUsageDecline: 3,
    sessionActivity: 3600,
    supportCost: 3300,
    engineeringCost: 8250,
    operationalCost: 11550,
    profitabilityScore: 82,
    marginPercentage: 72.5,
    healthScore: 80,
    churnRiskScore: 18,
    renewalDate: "2026-12-20",
    renewalValue: 450000,
    recentActivity: [
      { date: "2026-05-23", type: "support", description: "Training session completed for new team", severity: "info" },
    ],
    churnSignals: [],
    monthlyTrend: generateTrend(35000, 3300, 8250, 75, 15),
  },
  {
    id: "cust-013",
    name: "Pulse Digital Media",
    logo: "PD",
    segment: "SMB",
    industry: "Digital Media",
    accountOwner: "Marcus Rivera",
    lifecycleStage: "At Risk",
    onboardingStatus: "Complete",
    companySize: 85,
    leadSource: "Inbound Marketing",
    arr: 48000,
    mrr: 4000,
    contractValue: 48000,
    subscriptionStatus: "Active",
    billingCycle: "Monthly",
    failedPayments: 1,
    lastPaymentDate: "2026-05-01",
    paymentHistory: [
      { date: "2026-05-01", amount: 4000, status: "Paid" },
      { date: "2026-04-01", amount: 4000, status: "Failed" },
    ],
    upgrades: 0,
    downgrades: 0,
    ticketCount: 22,
    unresolvedTickets: 5,
    escalations: 2,
    slaBreaches: 1,
    csatScore: 58,
    supportHours: 38,
    issueCategories: ["Bugs", "Performance", "UX"],
    engineeringHours: 42,
    activeProjects: 1,
    delayedTasks: 3,
    bugCount: 11,
    sprintVelocity: 20,
    activeUsers: 28,
    featureAdoption: 42,
    loginFrequency: 45,
    engagementScore: 40,
    featureUsageDecline: 28,
    sessionActivity: 280,
    supportCost: 5700,
    engineeringCost: 6300,
    operationalCost: 12000,
    profitabilityScore: 22,
    marginPercentage: -25.0,
    healthScore: 35,
    churnRiskScore: 72,
    renewalDate: "2026-08-15",
    renewalValue: 48000,
    recentActivity: [
      { date: "2026-05-24", type: "support", description: "2 escalations this week", severity: "warning" },
      { date: "2026-05-22", type: "product", description: "Feature usage declined 28%", severity: "warning" },
    ],
    churnSignals: [
      { signal: "Feature usage declined 28%", severity: "high", source: "Mixpanel", detectedDate: "2026-05-22" },
      { signal: "CSAT score dropped to 58", severity: "medium", source: "Zendesk", detectedDate: "2026-05-15" },
      { signal: "11 open bugs impacting workflow", severity: "high", source: "Jira", detectedDate: "2026-05-20" },
    ],
    monthlyTrend: generateTrend(4000, 5700, 6300, 40, 22, true),
  },
  {
    id: "cust-014",
    name: "Horizon Payments",
    logo: "HP",
    segment: "Mid-Market",
    industry: "Payments",
    accountOwner: "Sarah Chen",
    lifecycleStage: "Active",
    onboardingStatus: "Complete",
    companySize: 420,
    leadSource: "Partner Referral",
    arr: 216000,
    mrr: 18000,
    contractValue: 240000,
    subscriptionStatus: "Active",
    billingCycle: "Annual",
    failedPayments: 0,
    lastPaymentDate: "2026-05-10",
    paymentHistory: [
      { date: "2026-05-10", amount: 18000, status: "Paid" },
    ],
    upgrades: 2,
    downgrades: 0,
    ticketCount: 7,
    unresolvedTickets: 1,
    escalations: 0,
    slaBreaches: 0,
    csatScore: 93,
    supportHours: 10,
    issueCategories: ["Feature Request"],
    engineeringHours: 15,
    activeProjects: 1,
    delayedTasks: 0,
    bugCount: 1,
    sprintVelocity: 38,
    activeUsers: 210,
    featureAdoption: 82,
    loginFrequency: 88,
    engagementScore: 85,
    featureUsageDecline: 0,
    sessionActivity: 2400,
    supportCost: 1500,
    engineeringCost: 2250,
    operationalCost: 3750,
    profitabilityScore: 91,
    marginPercentage: 79.2,
    healthScore: 90,
    churnRiskScore: 8,
    renewalDate: "2027-04-01",
    renewalValue: 240000,
    recentActivity: [
      { date: "2026-05-21", type: "account", description: "Upsell opportunity identified", severity: "info" },
    ],
    churnSignals: [],
    monthlyTrend: generateTrend(18000, 1500, 2250, 85, 7),
  },
  {
    id: "cust-015",
    name: "Nimbus Education",
    logo: "NE",
    segment: "SMB",
    industry: "EdTech",
    accountOwner: "James Park",
    lifecycleStage: "New",
    onboardingStatus: "In Progress",
    companySize: 55,
    leadSource: "Inbound Marketing",
    arr: 18000,
    mrr: 1500,
    contractValue: 18000,
    subscriptionStatus: "Active",
    billingCycle: "Monthly",
    failedPayments: 0,
    lastPaymentDate: "2026-05-01",
    paymentHistory: [
      { date: "2026-05-01", amount: 1500, status: "Paid" },
    ],
    upgrades: 0,
    downgrades: 0,
    ticketCount: 8,
    unresolvedTickets: 2,
    escalations: 0,
    slaBreaches: 0,
    csatScore: 78,
    supportHours: 15,
    issueCategories: ["Onboarding", "Training"],
    engineeringHours: 8,
    activeProjects: 0,
    delayedTasks: 0,
    bugCount: 1,
    sprintVelocity: 0,
    activeUsers: 22,
    featureAdoption: 35,
    loginFrequency: 55,
    engagementScore: 48,
    featureUsageDecline: 0,
    sessionActivity: 190,
    supportCost: 2250,
    engineeringCost: 1200,
    operationalCost: 3450,
    profitabilityScore: 45,
    marginPercentage: 38.9,
    healthScore: 55,
    churnRiskScore: 35,
    renewalDate: "2026-11-01",
    renewalValue: 18000,
    recentActivity: [
      { date: "2026-05-24", type: "account", description: "Onboarding session 2 of 4 completed", severity: "info" },
    ],
    churnSignals: [
      { signal: "Low feature adoption during onboarding", severity: "medium", source: "Mixpanel", detectedDate: "2026-05-20" },
    ],
    monthlyTrend: generateTrend(1500, 2250, 1200, 48, 8),
  },
  {
    id: "cust-016",
    name: "Apex Retail Group",
    logo: "AR",
    segment: "Enterprise",
    industry: "Retail",
    accountOwner: "Marcus Rivera",
    lifecycleStage: "Active",
    onboardingStatus: "Complete",
    companySize: 6800,
    leadSource: "Outbound Sales",
    arr: 840000,
    mrr: 70000,
    contractValue: 920000,
    subscriptionStatus: "Active",
    billingCycle: "Annual",
    failedPayments: 0,
    lastPaymentDate: "2026-05-18",
    paymentHistory: [
      { date: "2026-05-18", amount: 70000, status: "Paid" },
    ],
    upgrades: 3,
    downgrades: 0,
    ticketCount: 19,
    unresolvedTickets: 2,
    escalations: 0,
    slaBreaches: 0,
    csatScore: 89,
    supportHours: 30,
    issueCategories: ["Integration", "Feature Request", "Training"],
    engineeringHours: 70,
    activeProjects: 3,
    delayedTasks: 1,
    bugCount: 5,
    sprintVelocity: 42,
    activeUsers: 750,
    featureAdoption: 80,
    loginFrequency: 85,
    engagementScore: 83,
    featureUsageDecline: 0,
    sessionActivity: 8100,
    supportCost: 4500,
    engineeringCost: 10500,
    operationalCost: 15000,
    profitabilityScore: 89,
    marginPercentage: 78.6,
    healthScore: 88,
    churnRiskScore: 9,
    renewalDate: "2027-01-15",
    renewalValue: 920000,
    recentActivity: [
      { date: "2026-05-23", type: "product", description: "Rolled out to 3 new departments", severity: "info" },
    ],
    churnSignals: [],
    monthlyTrend: generateTrend(70000, 4500, 10500, 83, 19),
  },
  {
    id: "cust-017",
    name: "TerraVolt Energy",
    logo: "TV",
    segment: "Mid-Market",
    industry: "Clean Energy",
    accountOwner: "Sarah Chen",
    lifecycleStage: "At Risk",
    onboardingStatus: "Complete",
    companySize: 220,
    leadSource: "Conference",
    arr: 132000,
    mrr: 11000,
    contractValue: 132000,
    subscriptionStatus: "Active",
    billingCycle: "Monthly",
    failedPayments: 0,
    lastPaymentDate: "2026-05-01",
    paymentHistory: [
      { date: "2026-05-01", amount: 11000, status: "Paid" },
    ],
    upgrades: 0,
    downgrades: 1,
    ticketCount: 26,
    unresolvedTickets: 7,
    escalations: 3,
    slaBreaches: 2,
    csatScore: 55,
    supportHours: 48,
    issueCategories: ["Bugs", "Performance", "Data Sync"],
    engineeringHours: 85,
    activeProjects: 2,
    delayedTasks: 4,
    bugCount: 12,
    sprintVelocity: 24,
    activeUsers: 78,
    featureAdoption: 45,
    loginFrequency: 52,
    engagementScore: 48,
    featureUsageDecline: 22,
    sessionActivity: 640,
    supportCost: 7200,
    engineeringCost: 12750,
    operationalCost: 19950,
    profitabilityScore: 28,
    marginPercentage: -15.1,
    healthScore: 38,
    churnRiskScore: 68,
    renewalDate: "2026-09-01",
    renewalValue: 132000,
    recentActivity: [
      { date: "2026-05-24", type: "support", description: "3 escalations this month", severity: "warning" },
      { date: "2026-05-21", type: "product", description: "Product downgrade requested", severity: "warning" },
    ],
    churnSignals: [
      { signal: "Product downgrade requested", severity: "high", source: "Stripe", detectedDate: "2026-05-21" },
      { signal: "3 support escalations in 30 days", severity: "high", source: "Zendesk", detectedDate: "2026-05-24" },
      { signal: "Feature usage declining 22%", severity: "medium", source: "Mixpanel", detectedDate: "2026-05-18" },
    ],
    monthlyTrend: generateTrend(11000, 7200, 12750, 48, 26, true),
  },
  {
    id: "cust-018",
    name: "Catalyst Commerce",
    logo: "CC",
    segment: "Mid-Market",
    industry: "E-Commerce",
    accountOwner: "James Park",
    lifecycleStage: "Active",
    onboardingStatus: "Complete",
    companySize: 310,
    leadSource: "Product-Led Growth",
    arr: 168000,
    mrr: 14000,
    contractValue: 180000,
    subscriptionStatus: "Active",
    billingCycle: "Annual",
    failedPayments: 0,
    lastPaymentDate: "2026-05-05",
    paymentHistory: [
      { date: "2026-05-05", amount: 14000, status: "Paid" },
    ],
    upgrades: 1,
    downgrades: 0,
    ticketCount: 11,
    unresolvedTickets: 1,
    escalations: 0,
    slaBreaches: 0,
    csatScore: 86,
    supportHours: 16,
    issueCategories: ["Integration", "Feature Request"],
    engineeringHours: 25,
    activeProjects: 1,
    delayedTasks: 0,
    bugCount: 3,
    sprintVelocity: 33,
    activeUsers: 185,
    featureAdoption: 74,
    loginFrequency: 79,
    engagementScore: 76,
    featureUsageDecline: 2,
    sessionActivity: 2100,
    supportCost: 2400,
    engineeringCost: 3750,
    operationalCost: 6150,
    profitabilityScore: 84,
    marginPercentage: 70.4,
    healthScore: 81,
    churnRiskScore: 16,
    renewalDate: "2027-03-15",
    renewalValue: 180000,
    recentActivity: [
      { date: "2026-05-22", type: "product", description: "Integrated with 2 new third-party tools", severity: "info" },
    ],
    churnSignals: [],
    monthlyTrend: generateTrend(14000, 2400, 3750, 76, 11),
  },
  {
    id: "cust-019",
    name: "Quorum Legal Tech",
    logo: "QL",
    segment: "SMB",
    industry: "LegalTech",
    accountOwner: "Marcus Rivera",
    lifecycleStage: "Active",
    onboardingStatus: "Complete",
    companySize: 40,
    leadSource: "Inbound Marketing",
    arr: 30000,
    mrr: 2500,
    contractValue: 30000,
    subscriptionStatus: "Active",
    billingCycle: "Monthly",
    failedPayments: 0,
    lastPaymentDate: "2026-05-01",
    paymentHistory: [
      { date: "2026-05-01", amount: 2500, status: "Paid" },
    ],
    upgrades: 0,
    downgrades: 0,
    ticketCount: 4,
    unresolvedTickets: 0,
    escalations: 0,
    slaBreaches: 0,
    csatScore: 88,
    supportHours: 5,
    issueCategories: ["Training"],
    engineeringHours: 3,
    activeProjects: 0,
    delayedTasks: 0,
    bugCount: 0,
    sprintVelocity: 0,
    activeUsers: 28,
    featureAdoption: 62,
    loginFrequency: 70,
    engagementScore: 66,
    featureUsageDecline: 0,
    sessionActivity: 310,
    supportCost: 750,
    engineeringCost: 450,
    operationalCost: 1200,
    profitabilityScore: 87,
    marginPercentage: 76.0,
    healthScore: 78,
    churnRiskScore: 18,
    renewalDate: "2026-11-15",
    renewalValue: 30000,
    recentActivity: [
      { date: "2026-05-20", type: "product", description: "Completed advanced training module", severity: "info" },
    ],
    churnSignals: [],
    monthlyTrend: generateTrend(2500, 750, 450, 66, 4),
  },
  {
    id: "cust-020",
    name: "Aether Biotech",
    logo: "AB",
    segment: "Enterprise",
    industry: "Biotechnology",
    accountOwner: "Sarah Chen",
    lifecycleStage: "Active",
    onboardingStatus: "Complete",
    companySize: 1200,
    leadSource: "Outbound Sales",
    arr: 300000,
    mrr: 25000,
    contractValue: 330000,
    subscriptionStatus: "Active",
    billingCycle: "Annual",
    failedPayments: 0,
    lastPaymentDate: "2026-05-14",
    paymentHistory: [
      { date: "2026-05-14", amount: 25000, status: "Paid" },
    ],
    upgrades: 1,
    downgrades: 0,
    ticketCount: 14,
    unresolvedTickets: 2,
    escalations: 0,
    slaBreaches: 0,
    csatScore: 85,
    supportHours: 20,
    issueCategories: ["Compliance", "Integration"],
    engineeringHours: 40,
    activeProjects: 1,
    delayedTasks: 0,
    bugCount: 3,
    sprintVelocity: 35,
    activeUsers: 280,
    featureAdoption: 69,
    loginFrequency: 74,
    engagementScore: 72,
    featureUsageDecline: 4,
    sessionActivity: 2800,
    supportCost: 3000,
    engineeringCost: 6000,
    operationalCost: 9000,
    profitabilityScore: 80,
    marginPercentage: 70.0,
    healthScore: 78,
    churnRiskScore: 20,
    renewalDate: "2027-02-01",
    renewalValue: 330000,
    recentActivity: [
      { date: "2026-05-21", type: "account", description: "Compliance review completed successfully", severity: "info" },
    ],
    churnSignals: [],
    monthlyTrend: generateTrend(25000, 3000, 6000, 72, 14),
  },
  {
    id: "cust-021",
    name: "Vanguard Security",
    logo: "VS",
    segment: "Mid-Market",
    industry: "Cybersecurity",
    accountOwner: "James Park",
    lifecycleStage: "Active",
    onboardingStatus: "Complete",
    companySize: 190,
    leadSource: "Conference",
    arr: 156000,
    mrr: 13000,
    contractValue: 168000,
    subscriptionStatus: "Active",
    billingCycle: "Annual",
    failedPayments: 0,
    lastPaymentDate: "2026-05-09",
    paymentHistory: [
      { date: "2026-05-09", amount: 13000, status: "Paid" },
    ],
    upgrades: 1,
    downgrades: 0,
    ticketCount: 6,
    unresolvedTickets: 0,
    escalations: 0,
    slaBreaches: 0,
    csatScore: 91,
    supportHours: 8,
    issueCategories: ["Feature Request"],
    engineeringHours: 12,
    activeProjects: 0,
    delayedTasks: 0,
    bugCount: 1,
    sprintVelocity: 0,
    activeUsers: 120,
    featureAdoption: 79,
    loginFrequency: 84,
    engagementScore: 81,
    featureUsageDecline: 0,
    sessionActivity: 1450,
    supportCost: 1200,
    engineeringCost: 1800,
    operationalCost: 3000,
    profitabilityScore: 92,
    marginPercentage: 80.8,
    healthScore: 87,
    churnRiskScore: 10,
    renewalDate: "2026-12-10",
    renewalValue: 168000,
    recentActivity: [
      { date: "2026-05-23", type: "product", description: "Security audit feature heavily adopted", severity: "info" },
    ],
    churnSignals: [],
    monthlyTrend: generateTrend(13000, 1200, 1800, 81, 6),
  },
  {
    id: "cust-022",
    name: "Zenith Consulting",
    logo: "ZC",
    segment: "SMB",
    industry: "Consulting",
    accountOwner: "Marcus Rivera",
    lifecycleStage: "At Risk",
    onboardingStatus: "Complete",
    companySize: 30,
    leadSource: "Inbound Marketing",
    arr: 15000,
    mrr: 1250,
    contractValue: 15000,
    subscriptionStatus: "Active",
    billingCycle: "Monthly",
    failedPayments: 2,
    lastPaymentDate: "2026-04-01",
    paymentHistory: [
      { date: "2026-05-01", amount: 1250, status: "Failed" },
      { date: "2026-04-01", amount: 1250, status: "Paid" },
      { date: "2026-03-01", amount: 1250, status: "Failed" },
    ],
    upgrades: 0,
    downgrades: 0,
    ticketCount: 10,
    unresolvedTickets: 4,
    escalations: 1,
    slaBreaches: 1,
    csatScore: 62,
    supportHours: 18,
    issueCategories: ["Bugs", "UX"],
    engineeringHours: 22,
    activeProjects: 0,
    delayedTasks: 2,
    bugCount: 5,
    sprintVelocity: 0,
    activeUsers: 12,
    featureAdoption: 38,
    loginFrequency: 35,
    engagementScore: 32,
    featureUsageDecline: 35,
    sessionActivity: 120,
    supportCost: 2700,
    engineeringCost: 3300,
    operationalCost: 6000,
    profitabilityScore: 15,
    marginPercentage: -40.0,
    healthScore: 30,
    churnRiskScore: 75,
    renewalDate: "2026-07-01",
    renewalValue: 15000,
    recentActivity: [
      { date: "2026-05-24", type: "billing", description: "Payment failed — card expired", severity: "warning" },
      { date: "2026-05-22", type: "product", description: "Login frequency dropped to weekly", severity: "warning" },
    ],
    churnSignals: [
      { signal: "2 failed payments (expired card)", severity: "high", source: "Stripe", detectedDate: "2026-05-01" },
      { signal: "Usage declined 35% in 60 days", severity: "high", source: "Mixpanel", detectedDate: "2026-05-22" },
      { signal: "CSAT trending below threshold", severity: "medium", source: "Zendesk", detectedDate: "2026-05-15" },
    ],
    monthlyTrend: generateTrend(1250, 2700, 3300, 32, 10, true),
  },
  {
    id: "cust-023",
    name: "Atlas Logistics Pro",
    logo: "AL",
    segment: "Enterprise",
    industry: "Supply Chain",
    accountOwner: "Sarah Chen",
    lifecycleStage: "Active",
    onboardingStatus: "Complete",
    companySize: 2800,
    leadSource: "Partner Referral",
    arr: 516000,
    mrr: 43000,
    contractValue: 560000,
    subscriptionStatus: "Active",
    billingCycle: "Annual",
    failedPayments: 0,
    lastPaymentDate: "2026-05-16",
    paymentHistory: [
      { date: "2026-05-16", amount: 43000, status: "Paid" },
    ],
    upgrades: 2,
    downgrades: 0,
    ticketCount: 16,
    unresolvedTickets: 2,
    escalations: 0,
    slaBreaches: 0,
    csatScore: 90,
    supportHours: 24,
    issueCategories: ["Integration", "API", "Feature Request"],
    engineeringHours: 50,
    activeProjects: 2,
    delayedTasks: 0,
    bugCount: 3,
    sprintVelocity: 40,
    activeUsers: 420,
    featureAdoption: 81,
    loginFrequency: 86,
    engagementScore: 84,
    featureUsageDecline: 0,
    sessionActivity: 4500,
    supportCost: 3600,
    engineeringCost: 7500,
    operationalCost: 11100,
    profitabilityScore: 88,
    marginPercentage: 74.2,
    healthScore: 89,
    churnRiskScore: 9,
    renewalDate: "2026-12-01",
    renewalValue: 560000,
    recentActivity: [
      { date: "2026-05-23", type: "product", description: "API integration completed ahead of schedule", severity: "info" },
    ],
    churnSignals: [],
    monthlyTrend: generateTrend(43000, 3600, 7500, 84, 16),
  },
  {
    id: "cust-024",
    name: "Ember Creative",
    logo: "EC",
    segment: "SMB",
    industry: "Creative Agency",
    accountOwner: "James Park",
    lifecycleStage: "Active",
    onboardingStatus: "In Progress",
    companySize: 25,
    leadSource: "Product-Led Growth",
    arr: 12000,
    mrr: 1000,
    contractValue: 12000,
    subscriptionStatus: "Trial",
    billingCycle: "Monthly",
    failedPayments: 0,
    lastPaymentDate: "2026-05-01",
    paymentHistory: [
      { date: "2026-05-01", amount: 1000, status: "Paid" },
    ],
    upgrades: 0,
    downgrades: 0,
    ticketCount: 6,
    unresolvedTickets: 1,
    escalations: 0,
    slaBreaches: 0,
    csatScore: 82,
    supportHours: 10,
    issueCategories: ["Onboarding", "Training"],
    engineeringHours: 2,
    activeProjects: 0,
    delayedTasks: 0,
    bugCount: 0,
    sprintVelocity: 0,
    activeUsers: 15,
    featureAdoption: 28,
    loginFrequency: 60,
    engagementScore: 45,
    featureUsageDecline: 0,
    sessionActivity: 150,
    supportCost: 1500,
    engineeringCost: 300,
    operationalCost: 1800,
    profitabilityScore: 52,
    marginPercentage: 45.0,
    healthScore: 58,
    churnRiskScore: 30,
    renewalDate: "2026-08-01",
    renewalValue: 12000,
    recentActivity: [
      { date: "2026-05-24", type: "account", description: "Onboarding kickoff call completed", severity: "info" },
    ],
    churnSignals: [
      { signal: "Low feature adoption during trial", severity: "low", source: "Mixpanel", detectedDate: "2026-05-24" },
    ],
    monthlyTrend: generateTrend(1000, 1500, 300, 45, 6),
  },
  {
    id: "cust-025",
    name: "Nexus Telecom",
    logo: "NX",
    segment: "Enterprise",
    industry: "Telecommunications",
    accountOwner: "Marcus Rivera",
    lifecycleStage: "Active",
    onboardingStatus: "Complete",
    companySize: 3500,
    leadSource: "Outbound Sales",
    arr: 624000,
    mrr: 52000,
    contractValue: 680000,
    subscriptionStatus: "Active",
    billingCycle: "Annual",
    failedPayments: 0,
    lastPaymentDate: "2026-05-20",
    paymentHistory: [
      { date: "2026-05-20", amount: 52000, status: "Paid" },
    ],
    upgrades: 3,
    downgrades: 0,
    ticketCount: 20,
    unresolvedTickets: 3,
    escalations: 1,
    slaBreaches: 0,
    csatScore: 86,
    supportHours: 32,
    issueCategories: ["Integration", "Compliance", "Feature Request"],
    engineeringHours: 60,
    activeProjects: 2,
    delayedTasks: 1,
    bugCount: 4,
    sprintVelocity: 38,
    activeUsers: 480,
    featureAdoption: 76,
    loginFrequency: 82,
    engagementScore: 79,
    featureUsageDecline: 2,
    sessionActivity: 5200,
    supportCost: 4800,
    engineeringCost: 9000,
    operationalCost: 13800,
    profitabilityScore: 86,
    marginPercentage: 73.5,
    healthScore: 83,
    churnRiskScore: 14,
    renewalDate: "2027-04-15",
    renewalValue: 680000,
    recentActivity: [
      { date: "2026-05-22", type: "account", description: "Executive business review scheduled", severity: "info" },
    ],
    churnSignals: [],
    monthlyTrend: generateTrend(52000, 4800, 9000, 79, 20),
  },
];

// AI Insights for Profitability
export const profitabilityInsights: AIInsight[] = [
  {
    id: "ai-p-1",
    type: "critical",
    title: "High-cost account detected",
    description: "NovaTech Solutions consumes 38% more support resources than the average enterprise account while generating negative margin.",
    customer: "NovaTech Solutions",
    source: "Zendesk + Stripe",
    timestamp: "2026-05-25T09:15:00",
    impact: "$39,900 operational cost against $360K ARR",
  },
  {
    id: "ai-p-2",
    type: "warning",
    title: "Declining profitability trend",
    description: "Orbital Dynamics margin has dropped from 15% to -18.9% over the last 3 months due to escalating support and engineering costs.",
    customer: "Orbital Dynamics",
    source: "Jira + Zendesk",
    timestamp: "2026-05-25T08:30:00",
    impact: "$27,300 operational cost on $144K ARR",
  },
  {
    id: "ai-p-3",
    type: "opportunity",
    title: "Expansion revenue opportunity",
    description: "CloudScale AI has the highest engagement score (95) and profitability (86%). Strong candidate for upsell with $110K expansion in pipeline.",
    customer: "CloudScale AI",
    source: "HubSpot + Mixpanel",
    timestamp: "2026-05-25T07:45:00",
    impact: "Potential $110K ARR expansion",
  },
  {
    id: "ai-p-4",
    type: "warning",
    title: "Support cost anomaly",
    description: "Pulse Digital Media's support costs ($5,700/mo) exceed their MRR ($4,000/mo). 11 open bugs are driving repeat tickets.",
    customer: "Pulse Digital Media",
    source: "Zendesk + Jira",
    timestamp: "2026-05-24T16:00:00",
    impact: "-25% margin, net loss of $12K annually",
  },
  {
    id: "ai-p-5",
    type: "info",
    title: "Top performer spotlight",
    description: "Meridian Health Systems delivers the highest absolute margin in the portfolio at $780K annual profit with 81.3% margin.",
    customer: "Meridian Health Systems",
    source: "Stripe + Jira",
    timestamp: "2026-05-24T14:30:00",
    impact: "$960K ARR with minimal operational cost",
  },
];

// AI Insights for Churn
export const churnInsights: AIInsight[] = [
  {
    id: "ai-c-1",
    type: "critical",
    title: "Imminent churn — cancellation inquiry",
    description: "Vertex Analytics has requested cancellation information, has 4 failed payments, and only 3 of 45 users remain active. Renewal in 21 days.",
    customer: "Vertex Analytics",
    source: "Zendesk + Stripe + Mixpanel",
    timestamp: "2026-05-25T10:00:00",
    impact: "$24K ARR at immediate risk",
  },
  {
    id: "ai-c-2",
    type: "critical",
    title: "Champion departure — high-value account",
    description: "NovaTech Solutions' primary champion has left the company. Combined with 48% usage decline and payment failures, churn probability is 82%.",
    customer: "NovaTech Solutions",
    source: "HubSpot + Mixpanel",
    timestamp: "2026-05-25T09:00:00",
    impact: "$360K ARR at risk, renewal in 67 days",
  },
  {
    id: "ai-c-3",
    type: "warning",
    title: "Payment failure pattern before renewal",
    description: "Orbital Dynamics has 3 consecutive failed payments with renewal approaching in 51 days. Active users have declined 64%.",
    customer: "Orbital Dynamics",
    source: "Stripe + Mixpanel",
    timestamp: "2026-05-25T08:15:00",
    impact: "$144K ARR at risk",
  },
  {
    id: "ai-c-4",
    type: "warning",
    title: "Engagement cliff detected",
    description: "TerraVolt Energy engagement has dropped below the churn threshold. 3 escalations and a product downgrade signal growing dissatisfaction.",
    customer: "TerraVolt Energy",
    source: "Mixpanel + Zendesk",
    timestamp: "2026-05-24T17:00:00",
    impact: "$132K ARR at risk",
  },
  {
    id: "ai-c-5",
    type: "info",
    title: "Early warning — new account adoption",
    description: "Nimbus Education is showing below-average feature adoption during onboarding. Early intervention could prevent future risk.",
    customer: "Nimbus Education",
    source: "Mixpanel",
    timestamp: "2026-05-24T15:00:00",
    impact: "$18K ARR — preventive action recommended",
  },
];

export const notifications: Notification[] = [
  { id: "n1", title: "Critical Churn Alert", message: "Vertex Analytics has requested cancellation information", type: "alert", time: "2 min ago", read: false },
  { id: "n2", title: "Payment Failure", message: "Orbital Dynamics — 3rd consecutive failed payment", type: "alert", time: "1h ago", read: false },
  { id: "n3", title: "Expansion Opportunity", message: "CloudScale AI — $110K upsell in pipeline", type: "success", time: "3h ago", read: false },
  { id: "n4", title: "SLA Breach", message: "TerraVolt Energy — Priority ticket exceeded response time", type: "alert", time: "5h ago", read: true },
  { id: "n5", title: "New Customer Onboarded", message: "Ember Creative completed kickoff call", type: "info", time: "1d ago", read: true },
];

// Aggregate metrics
export function getAggregateMetrics() {
  const totalARR = customers.reduce((s, c) => s + c.arr, 0);
  const totalMRR = customers.reduce((s, c) => s + c.mrr, 0);
  const totalOperationalCost = customers.reduce((s, c) => s + c.operationalCost, 0);
  const avgMargin = customers.reduce((s, c) => s + c.marginPercentage, 0) / customers.length;
  const avgHealth = customers.reduce((s, c) => s + c.healthScore, 0) / customers.length;
  const atRiskCustomers = customers.filter((c) => c.churnRiskScore >= 50);
  const arrAtRisk = atRiskCustomers.reduce((s, c) => s + c.arr, 0);
  const mostProfitable = [...customers].sort((a, b) => b.profitabilityScore - a.profitabilityScore)[0];
  const highestSupportBurden = [...customers].sort((a, b) => b.supportCost - a.supportCost)[0];
  const grossMargin = ((totalARR - totalOperationalCost * 12) / totalARR) * 100;

  return {
    totalARR,
    totalMRR,
    totalOperationalCost,
    avgMargin,
    avgHealth,
    atRiskCount: atRiskCustomers.length,
    arrAtRisk,
    mostProfitable,
    highestSupportBurden,
    grossMargin,
    totalCustomers: customers.length,
    enterpriseCount: customers.filter((c) => c.segment === "Enterprise").length,
    midMarketCount: customers.filter((c) => c.segment === "Mid-Market").length,
    smbCount: customers.filter((c) => c.segment === "SMB").length,
    declinedEngagement: customers.filter((c) => c.featureUsageDecline > 15).length,
    failedPaymentAccounts: customers.filter((c) => c.failedPayments > 0).length,
  };
}

// ─── AI Usage Data ──────────────────────────────────────────────────
export const aiModelUsage: AIModelUsage[] = [
  {
    id: "ai-m-1",
    model: "GPT-4o",
    provider: "OpenAI",
    useCase: "Customer Profitability Insights",
    category: "Data Analysis",
    status: "active",
    inputTokens: 4_820_000,
    outputTokens: 1_460_000,
    totalTokens: 6_280_000,
    requests: 18_420,
    avgLatencyMs: 1240,
    costPerMille: 0.005,
    totalCost: 31.40,
    lastUsed: "2026-05-26T14:32:00",
  },
  {
    id: "ai-m-2",
    model: "Claude 3.5 Sonnet",
    provider: "Anthropic",
    useCase: "Churn Risk Analysis & Scoring",
    category: "Churn Prediction",
    status: "active",
    inputTokens: 6_150_000,
    outputTokens: 2_080_000,
    totalTokens: 8_230_000,
    requests: 24_610,
    avgLatencyMs: 980,
    costPerMille: 0.003,
    totalCost: 24.69,
    lastUsed: "2026-05-26T15:01:00",
  },
  {
    id: "ai-m-3",
    model: "GPT-4o Mini",
    provider: "OpenAI",
    useCase: "Executive Report Summarization",
    category: "Summarization",
    status: "active",
    inputTokens: 2_340_000,
    outputTokens: 680_000,
    totalTokens: 3_020_000,
    requests: 9_870,
    avgLatencyMs: 420,
    costPerMille: 0.00015,
    totalCost: 0.45,
    lastUsed: "2026-05-26T12:18:00",
  },
  {
    id: "ai-m-4",
    model: "DALL·E 3",
    provider: "OpenAI",
    useCase: "Report Charts & Visual Assets",
    category: "Image Processing",
    status: "active",
    inputTokens: 0,
    outputTokens: 0,
    totalTokens: 0,
    requests: 1_240,
    avgLatencyMs: 3800,
    costPerMille: 0,
    totalCost: 49.60,
    lastUsed: "2026-05-25T18:45:00",
  },
  {
    id: "ai-m-5",
    model: "Claude 3 Haiku",
    provider: "Anthropic",
    useCase: "Support Ticket Classification",
    category: "Content Generation",
    status: "active",
    inputTokens: 8_920_000,
    outputTokens: 1_120_000,
    totalTokens: 10_040_000,
    requests: 42_300,
    avgLatencyMs: 210,
    costPerMille: 0.00025,
    totalCost: 2.51,
    lastUsed: "2026-05-26T15:12:00",
  },
  {
    id: "ai-m-6",
    model: "Gemini 1.5 Pro",
    provider: "Google",
    useCase: "Cross-Platform Data Correlation",
    category: "Data Analysis",
    status: "active",
    inputTokens: 3_480_000,
    outputTokens: 920_000,
    totalTokens: 4_400_000,
    requests: 8_640,
    avgLatencyMs: 1560,
    costPerMille: 0.0035,
    totalCost: 15.40,
    lastUsed: "2026-05-26T11:05:00",
  },
  {
    id: "ai-m-7",
    model: "GPT-4o",
    provider: "OpenAI",
    useCase: "AI Recommendation Engine",
    category: "Recommendations",
    status: "active",
    inputTokens: 5_640_000,
    outputTokens: 1_880_000,
    totalTokens: 7_520_000,
    requests: 15_280,
    avgLatencyMs: 1380,
    costPerMille: 0.005,
    totalCost: 37.60,
    lastUsed: "2026-05-26T14:55:00",
  },
  {
    id: "ai-m-8",
    model: "Stable Diffusion XL",
    provider: "Stability AI",
    useCase: "Customer Dashboard Thumbnails",
    category: "Image Processing",
    status: "limited",
    inputTokens: 0,
    outputTokens: 0,
    totalTokens: 0,
    requests: 620,
    avgLatencyMs: 4200,
    costPerMille: 0,
    totalCost: 12.40,
    lastUsed: "2026-05-24T09:30:00",
  },
  {
    id: "ai-m-9",
    model: "SaaS OS Scoring v2",
    provider: "Internal",
    useCase: "Health Score Computation",
    category: "Churn Prediction",
    status: "active",
    inputTokens: 12_400_000,
    outputTokens: 3_200_000,
    totalTokens: 15_600_000,
    requests: 52_100,
    avgLatencyMs: 85,
    costPerMille: 0,
    totalCost: 0,
    lastUsed: "2026-05-26T15:15:00",
  },
  {
    id: "ai-m-10",
    model: "GPT-3.5 Turbo",
    provider: "OpenAI",
    useCase: "Notification Copy Generation",
    category: "Content Generation",
    status: "deprecated",
    inputTokens: 1_200_000,
    outputTokens: 380_000,
    totalTokens: 1_580_000,
    requests: 5_420,
    avgLatencyMs: 320,
    costPerMille: 0.0005,
    totalCost: 0.79,
    lastUsed: "2026-04-30T23:59:00",
  },
];

export function getAIUsageSummary(): AIUsageSummary {
  const activeModels = aiModelUsage.filter((m) => m.status === "active");
  const totalTokensUsed = aiModelUsage.reduce((s, m) => s + m.totalTokens, 0);
  const totalCost = aiModelUsage.reduce((s, m) => s + m.totalCost, 0);
  const totalRequests = aiModelUsage.reduce((s, m) => s + m.requests, 0);
  const avgLatencyMs = Math.round(
    activeModels.reduce((s, m) => s + m.avgLatencyMs, 0) / activeModels.length
  );

  // Group tokens by category
  const catMap = new Map<string, { tokens: number; cost: number }>();
  aiModelUsage.forEach((m) => {
    const existing = catMap.get(m.category) || { tokens: 0, cost: 0 };
    catMap.set(m.category, {
      tokens: existing.tokens + m.totalTokens,
      cost: existing.cost + m.totalCost,
    });
  });
  const tokensByCategory = Array.from(catMap.entries())
    .map(([category, vals]) => ({ category, ...vals }))
    .sort((a, b) => b.tokens - a.tokens);

  // Simulated daily usage for the last 14 days
  const dailyUsage = Array.from({ length: 14 }, (_, i) => {
    const d = new Date("2026-05-26");
    d.setDate(d.getDate() - (13 - i));
    const base = totalRequests / 30;
    const noise = 0.7 + Math.random() * 0.6;
    const requests = Math.round(base * noise);
    const tokens = Math.round((totalTokensUsed / 30) * noise);
    const cost = parseFloat(((totalCost / 30) * noise).toFixed(2));
    return {
      date: d.toISOString().slice(0, 10),
      tokens,
      cost,
      requests,
    };
  });

  return {
    totalTokensUsed,
    totalCost,
    totalRequests,
    activeModels: activeModels.length,
    avgLatencyMs,
    costTrend: -8.3, // 8.3% decrease vs prior month (positive signal)
    tokensByCategory,
    dailyUsage,
  };
}

// ─── Executive Overview Metrics ─────────────────────────────────────
export function getExecutiveMetrics() {
  const base = getAggregateMetrics();
  const healthy = customers.filter((c) => c.healthScore >= 80).length;
  const needsAttention = customers.filter((c) => c.healthScore >= 60 && c.healthScore < 80).length;
  const atRisk = customers.filter((c) => c.healthScore < 60).length;
  const avgCsat = customers.reduce((s, c) => s + c.csatScore, 0) / customers.length;
  const avgEngagement = customers.reduce((s, c) => s + c.engagementScore, 0) / customers.length;
  // Net Revenue Retention proxy from upgrades/downgrades
  const expansion = customers.reduce((s, c) => s + c.upgrades * 18000, 0);
  const contraction = customers.reduce((s, c) => s + c.downgrades * 14000, 0);
  const churned = customers.filter((c) => c.lifecycleStage === "Churning").reduce((s, c) => s + c.arr, 0);
  const nrr = ((base.totalARR + expansion - contraction - churned) / base.totalARR) * 100;
  const topAccounts = [...customers].sort((a, b) => b.arr - a.arr).slice(0, 5);
  // Portfolio ARR trend (sum of monthly revenue across all customers, annualized)
  const portfolioTrend = months.map((month, i) => {
    const monthRevenue = customers.reduce((s, c) => s + (c.monthlyTrend[i]?.revenue || c.mrr), 0);
    return { month, arr: Math.round(monthRevenue * 12), mrr: Math.round(monthRevenue) };
  });
  return {
    ...base,
    healthy,
    needsAttention,
    atRisk,
    avgCsat,
    avgEngagement,
    nrr,
    npsScore: 48,
    topAccounts,
    portfolioTrend,
    expansion,
    contraction,
  };
}

// Aggregated recent activity across the portfolio for the executive feed
export function getPortfolioActivity() {
  const items = customers.flatMap((c) =>
    c.recentActivity.map((a) => ({ ...a, customer: c.name, logo: c.logo }))
  );
  return items.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()).slice(0, 12);
}

// ─── Revenue Operations Data ────────────────────────────────────────
export const pipelineDeals: PipelineDeal[] = [
  { id: "deal-1", customer: "CloudScale AI", logo: "CA", type: "Expansion", stage: "Negotiation", value: 110000, probability: 80, owner: "Sarah Chen", closeDate: "2026-07-10", source: "HubSpot" },
  { id: "deal-2", customer: "Meridian Health Systems", logo: "MH", type: "Renewal", stage: "Closing", value: 1100000, probability: 90, owner: "Sarah Chen", closeDate: "2026-07-01", source: "HubSpot" },
  { id: "deal-3", customer: "Apex Retail Group", logo: "AR", type: "Upsell", stage: "Proposal", value: 140000, probability: 60, owner: "Marcus Rivera", closeDate: "2026-08-15", source: "HubSpot" },
  { id: "deal-4", customer: "Nexus Telecom", logo: "NX", type: "Expansion", stage: "Discovery", value: 95000, probability: 35, owner: "Marcus Rivera", closeDate: "2026-09-05", source: "HubSpot" },
  { id: "deal-5", customer: "Beacon Financial", logo: "BF", type: "Upsell", stage: "Proposal", value: 48000, probability: 55, owner: "Marcus Rivera", closeDate: "2026-08-20", source: "HubSpot" },
  { id: "deal-6", customer: "Atlas Logistics Pro", logo: "AL", type: "Renewal", stage: "Negotiation", value: 560000, probability: 75, owner: "Sarah Chen", closeDate: "2026-07-25", source: "HubSpot" },
  { id: "deal-7", customer: "Horizon Payments", logo: "HP", type: "Expansion", stage: "Closing", value: 60000, probability: 85, owner: "Sarah Chen", closeDate: "2026-07-08", source: "HubSpot" },
  { id: "deal-8", customer: "Catalyst Commerce", logo: "CC", type: "Upsell", stage: "Discovery", value: 36000, probability: 30, owner: "James Park", closeDate: "2026-09-18", source: "HubSpot" },
  { id: "deal-9", customer: "Vanguard Security", logo: "VS", type: "Expansion", stage: "Proposal", value: 42000, probability: 50, owner: "James Park", closeDate: "2026-08-12", source: "HubSpot" },
  { id: "deal-10", customer: "Forge Manufacturing", logo: "FM", type: "Renewal", stage: "Negotiation", value: 450000, probability: 70, owner: "Sarah Chen", closeDate: "2026-08-01", source: "HubSpot" },
  { id: "deal-11", customer: "TechFlow (New)", logo: "TF", type: "New Business", stage: "Proposal", value: 180000, probability: 45, owner: "James Park", closeDate: "2026-09-30", source: "HubSpot" },
  { id: "deal-12", customer: "BrightPath (New)", logo: "BP", type: "New Business", stage: "Discovery", value: 90000, probability: 25, owner: "James Park", closeDate: "2026-10-15", source: "HubSpot" },
];

export function getRevenueMetrics() {
  const totalARR = customers.reduce((s, c) => s + c.arr, 0);
  const totalMRR = customers.reduce((s, c) => s + c.mrr, 0);
  const newMrr = 42000;
  const expansionMrr = customers.reduce((s, c) => s + c.upgrades * 1500, 0);
  const contractionMrr = customers.reduce((s, c) => s + c.downgrades * 1200, 0);
  const churnedMrr = customers.filter((c) => c.lifecycleStage === "Churning").reduce((s, c) => s + c.mrr, 0);
  const startMrr = totalMRR - newMrr - expansionMrr + contractionMrr + churnedMrr;
  const nrr = ((startMrr + expansionMrr - contractionMrr - churnedMrr) / startMrr) * 100;
  const grr = ((startMrr - contractionMrr - churnedMrr) / startMrr) * 100;

  const openDeals = pipelineDeals.filter((d) => d.stage !== "Closed Won");
  const totalPipeline = openDeals.reduce((s, d) => s + d.value, 0);
  const weightedPipeline = openDeals.reduce((s, d) => s + d.value * (d.probability / 100), 0);

  // Upcoming renewals in next 120 days
  const now = new Date("2026-06-18");
  const upcomingRenewals = [...customers]
    .filter((c) => {
      const d = new Date(c.renewalDate);
      const diff = (d.getTime() - now.getTime()) / 86400000;
      return diff >= 0 && diff <= 120;
    })
    .sort((a, b) => new Date(a.renewalDate).getTime() - new Date(b.renewalDate).getTime());
  const renewalsValue = upcomingRenewals.reduce((s, c) => s + c.renewalValue, 0);
  const renewalsAtRisk = upcomingRenewals.filter((c) => c.churnRiskScore >= 50).reduce((s, c) => s + c.renewalValue, 0);

  const failedPaymentAccounts = customers.filter((c) => c.failedPayments > 0);
  const revenueInDunning = failedPaymentAccounts.reduce((s, c) => s + c.mrr, 0);

  // MRR movement trend (last 12 months) — simulated waterfall components
  const mrrTrend = months.map((month, i) => {
    const growth = 1 + i * 0.012;
    return {
      month,
      mrr: Math.round(startMrr * growth),
      new: Math.round(8000 + Math.random() * 6000),
      expansion: Math.round(4000 + Math.random() * 4000),
      churn: -Math.round(2000 + Math.random() * 3000),
    };
  });

  return {
    totalARR,
    totalMRR,
    newMrr,
    expansionMrr,
    contractionMrr,
    churnedMrr,
    nrr,
    grr,
    totalPipeline,
    weightedPipeline,
    openDealCount: openDeals.length,
    upcomingRenewals,
    renewalsValue,
    renewalsAtRisk,
    failedPaymentAccounts,
    revenueInDunning,
    mrrTrend,
    quarterlyForecast: Math.round(totalMRR * 3 + weightedPipeline * 0.4),
  };
}

// ─── Team Efficiency Data ───────────────────────────────────────────
function ownerStats(owner: string) {
  const book = customers.filter((c) => c.accountOwner === owner);
  const count = book.length || 1;
  return {
    accountsManaged: book.length,
    arrManaged: book.reduce((s, c) => s + c.arr, 0),
    avgHealthScore: Math.round(book.reduce((s, c) => s + c.healthScore, 0) / count),
    renewalsSecured: book.filter((c) => c.lifecycleStage === "Active").length,
    expansionArr: book.reduce((s, c) => s + c.upgrades * 18000, 0),
  };
}

const outputTrend = (base: number, growth = true) =>
  months.map((month, i) => ({
    month,
    value: Math.round(base * (0.85 + Math.random() * 0.25 + (growth ? i * 0.01 : 0))),
  }));

const sc = ownerStats("Sarah Chen");
const mr = ownerStats("Marcus Rivera");
const jp = ownerStats("James Park");

export const teamMembers: TeamMember[] = [
  {
    id: "tm-1", name: "Sarah Chen", role: "Enterprise CSM", team: "Customer Success", avatar: "SC",
    email: "sarah.chen@saasco.com", status: "busy",
    accountsManaged: sc.accountsManaged, arrManaged: sc.arrManaged, avgHealthScore: sc.avgHealthScore,
    utilization: 88, renewalsSecured: sc.renewalsSecured, expansionArr: sc.expansionArr, csat: 92,
    monthlyOutput: outputTrend(sc.arrManaged / 1000),
  },
  {
    id: "tm-2", name: "Marcus Rivera", role: "Customer Success Manager", team: "Customer Success", avatar: "MR",
    email: "marcus.rivera@saasco.com", status: "overloaded",
    accountsManaged: mr.accountsManaged, arrManaged: mr.arrManaged, avgHealthScore: mr.avgHealthScore,
    utilization: 96, renewalsSecured: mr.renewalsSecured, expansionArr: mr.expansionArr, csat: 79,
    monthlyOutput: outputTrend(mr.arrManaged / 1000),
  },
  {
    id: "tm-3", name: "James Park", role: "SMB Account Executive", team: "Sales", avatar: "JP",
    email: "james.park@saasco.com", status: "available",
    accountsManaged: jp.accountsManaged, arrManaged: jp.arrManaged, avgHealthScore: jp.avgHealthScore,
    utilization: 72, dealsWon: 9, quotaAttainment: 84, expansionArr: jp.expansionArr,
    monthlyOutput: outputTrend(jp.arrManaged / 1000),
  },
  {
    id: "tm-4", name: "Priya Patel", role: "Enterprise Account Executive", team: "Sales", avatar: "PP",
    email: "priya.patel@saasco.com", status: "busy",
    accountsManaged: 6, arrManaged: 1480000, avgHealthScore: 81, utilization: 90,
    dealsWon: 14, quotaAttainment: 118, expansionArr: 220000,
    monthlyOutput: outputTrend(124, true),
  },
  {
    id: "tm-5", name: "Daniel Okafor", role: "Support Team Lead", team: "Support", avatar: "DO",
    email: "daniel.okafor@saasco.com", status: "busy",
    accountsManaged: 0, arrManaged: 0, avgHealthScore: 0, utilization: 84,
    ticketsResolved: 342, avgResponseHours: 1.8, csat: 88, slaCompliance: 94,
    monthlyOutput: outputTrend(320, true),
  },
  {
    id: "tm-6", name: "Emily Zhang", role: "Senior Support Engineer", team: "Support", avatar: "EZ",
    email: "emily.zhang@saasco.com", status: "overloaded",
    accountsManaged: 0, arrManaged: 0, avgHealthScore: 0, utilization: 97,
    ticketsResolved: 418, avgResponseHours: 2.4, csat: 83, slaCompliance: 89,
    monthlyOutput: outputTrend(400, true),
  },
  {
    id: "tm-7", name: "Tom Becker", role: "Engineering Lead", team: "Engineering", avatar: "TB",
    email: "tom.becker@saasco.com", status: "busy",
    accountsManaged: 0, arrManaged: 0, avgHealthScore: 0, utilization: 86,
    sprintVelocity: 42, bugsResolved: 96,
    monthlyOutput: outputTrend(40, true),
  },
  {
    id: "tm-8", name: "Aisha Khan", role: "Solutions Engineer", team: "Engineering", avatar: "AK",
    email: "aisha.khan@saasco.com", status: "available",
    accountsManaged: 0, arrManaged: 0, avgHealthScore: 0, utilization: 68,
    sprintVelocity: 36, bugsResolved: 74,
    monthlyOutput: outputTrend(34, true),
  },
];

export function getTeamSummary() {
  const teams: TeamMember["team"][] = ["Sales", "Customer Success", "Support", "Engineering"];
  const byTeam = teams.map((team) => {
    const members = teamMembers.filter((m) => m.team === team);
    const count = members.length || 1;
    return {
      team,
      headcount: members.length,
      avgUtilization: Math.round(members.reduce((s, m) => s + m.utilization, 0) / count),
      arrManaged: members.reduce((s, m) => s + m.arrManaged, 0),
      accountsManaged: members.reduce((s, m) => s + m.accountsManaged, 0),
    };
  });
  const avgUtilization = Math.round(teamMembers.reduce((s, m) => s + m.utilization, 0) / teamMembers.length);
  const overloaded = teamMembers.filter((m) => m.status === "overloaded").length;
  const totalTicketsResolved = teamMembers.reduce((s, m) => s + (m.ticketsResolved || 0), 0);
  const avgCsat = Math.round(
    teamMembers.filter((m) => m.csat).reduce((s, m) => s + (m.csat || 0), 0) /
      teamMembers.filter((m) => m.csat).length
  );
  return { byTeam, avgUtilization, overloaded, headcount: teamMembers.length, totalTicketsResolved, avgCsat };
}

// Customers belonging to a given team member's book of business
export function getMemberBook(name: string): Customer[] {
  return customers.filter((c) => c.accountOwner === name).sort((a, b) => b.arr - a.arr);
}

// ─── AI Recommendations Data ────────────────────────────────────────
export const recommendations: Recommendation[] = [
  {
    id: "rec-1",
    title: "Launch executive save play for Vertex Analytics",
    description: "Vertex Analytics has requested cancellation info with 4 failed payments and 93% usage decline. A leadership-led save play within 7 days is the highest-leverage retention action this week.",
    category: "Retention", priority: "critical", customer: "Vertex Analytics",
    impact: "$24K ARR", impactValue: 24000, confidence: 91, effort: "Medium",
    sources: ["Zendesk", "Stripe", "Mixpanel"], actionType: "escalation",
    rationale: [
      "Cancellation information requested via Zendesk (May 22)",
      "4 consecutive failed payments in Stripe",
      "Only 3 of 45 seats active — 93% engagement drop",
    ],
  },
  {
    id: "rec-2",
    title: "Close $110K expansion at CloudScale AI",
    description: "CloudScale AI shows the portfolio's highest engagement (95) and margin (86%). A $110K expansion is already in pipeline at 80% probability — prioritize an executive outreach to accelerate close.",
    category: "Growth", priority: "high", customer: "CloudScale AI",
    impact: "$110K ARR", impactValue: 110000, confidence: 87, effort: "Low",
    sources: ["HubSpot", "Mixpanel"], actionType: "outreach",
    rationale: [
      "Expansion deal in Negotiation stage (80% probability)",
      "Highest engagement score in portfolio (95)",
      "4 product upgrades in trailing 12 months",
    ],
  },
  {
    id: "rec-3",
    title: "Escalate NovaTech Solutions champion departure",
    description: "NovaTech's primary champion left the company while usage dropped 48% and payments failed twice. Combined churn probability is 82% against $360K ARR — assign a recovery owner immediately.",
    category: "Retention", priority: "critical", customer: "NovaTech Solutions",
    impact: "$360K ARR", impactValue: 360000, confidence: 84, effort: "High",
    sources: ["HubSpot", "Mixpanel", "Stripe"], actionType: "escalation",
    rationale: [
      "Champion contact departed (HubSpot, May 20)",
      "Feature adoption declined 48% in 30 days",
      "2 consecutive failed payments before renewal",
    ],
  },
  {
    id: "rec-4",
    title: "Re-engage Orbital Dynamics before renewal",
    description: "Orbital Dynamics has 3 failed payments and a 64% active-user decline with renewal in ~27 days. A win-back campaign plus billing recovery can protect $144K ARR.",
    category: "Retention", priority: "high", customer: "Orbital Dynamics",
    impact: "$144K ARR", impactValue: 144000, confidence: 78, effort: "Medium",
    sources: ["Stripe", "Mixpanel", "Zendesk"], actionType: "campaign",
    rationale: [
      "3 consecutive failed payments in Stripe",
      "Active users down 64% (Mixpanel)",
      "Renewal date within 30 days",
    ],
  },
  {
    id: "rec-5",
    title: "Reduce support burden on NovaTech & Orbital",
    description: "Two accounts consume 38% above-average support resources at negative margin. Routing recurring bug tickets to a dedicated Jira swimlane could recover ~$18K/mo in operational cost.",
    category: "Cost", priority: "high", customer: "NovaTech Solutions",
    impact: "$18K/mo cost", impactValue: 216000, confidence: 73, effort: "Medium",
    sources: ["Zendesk", "Jira"], actionType: "review",
    rationale: [
      "Support cost exceeds MRR on both accounts",
      "18 open bugs driving repeat tickets",
      "5 escalations to engineering this quarter",
    ],
  },
  {
    id: "rec-6",
    title: "Upsell Apex Retail Group on usage expansion",
    description: "Apex Retail rolled out to 3 new departments with 80% feature adoption. A $140K upsell is in Proposal stage — package an ROI showcase to move it to close.",
    category: "Revenue", priority: "medium", customer: "Apex Retail Group",
    impact: "$140K ARR", impactValue: 140000, confidence: 69, effort: "Low",
    sources: ["HubSpot", "Mixpanel"], actionType: "campaign",
    rationale: [
      "Upsell deal in Proposal stage ($140K)",
      "Rolled out to 3 new departments (May 23)",
      "Feature adoption at 80% and rising",
    ],
  },
  {
    id: "rec-7",
    title: "Rebalance Marcus Rivera's overloaded book",
    description: "Marcus Rivera is at 96% utilization managing the lowest-health book in Customer Success. Redistributing 2 at-risk accounts could lift portfolio health and protect renewals.",
    category: "Efficiency", priority: "medium",
    impact: "Team capacity", impactValue: 0, confidence: 65, effort: "Low",
    sources: ["Internal"], actionType: "review",
    rationale: [
      "96% utilization — flagged overloaded",
      "Manages multiple at-risk accounts (NovaTech, TerraVolt, Pulse)",
      "CSAT trailing team average",
    ],
  },
  {
    id: "rec-8",
    title: "Accelerate Nimbus Education onboarding",
    description: "Nimbus Education shows below-average adoption during onboarding. Early intervention with a guided activation plan reduces first-year churn risk on this new account.",
    category: "Retention", priority: "low", customer: "Nimbus Education",
    impact: "$18K ARR", impactValue: 18000, confidence: 62, effort: "Low",
    sources: ["Mixpanel"], actionType: "outreach",
    rationale: [
      "Low feature adoption during onboarding (35%)",
      "Onboarding 2 of 4 sessions complete",
      "New-account lifecycle stage",
    ],
  },
];

export function getRecommendationSummary() {
  const totalImpact = recommendations
    .filter((r) => r.category !== "Efficiency" && r.impactValue > 0 && r.impact.includes("ARR"))
    .reduce((s, r) => s + r.impactValue, 0);
  return {
    total: recommendations.length,
    critical: recommendations.filter((r) => r.priority === "critical").length,
    high: recommendations.filter((r) => r.priority === "high").length,
    avgConfidence: Math.round(recommendations.reduce((s, r) => s + r.confidence, 0) / recommendations.length),
    totalImpact,
  };
}
